-- require('tmux').setup({
--   copy_sync = { enable = true }, -- Sync clipboard between Neovim and tmux
--   navigation = {
--     enable_default_keybindings = true,
--     persist_zoom = true, -- Persist zoom on tmux panes
--   },
--   resize = {
--     enable_default_keybindings = true,
--   },
-- })
